# Cloudflare Pages configuration for HKAFF 2025 Selector
name = "hkaff-2025-selector"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "frontend/dist"

# Build configuration
[build]
command = "cd frontend && npm ci && npm run build"
watch_dir = "frontend/src"

# Environment variables
[vars]
NODE_VERSION = "18"

# Development settings for local Pages development
[dev]
port = 8788
local_protocol = "http"