name = "hkaff-2025-selector"
compatibility_date = "2025-10-16"

[observability]
enabled = true

[assets]
directory = "dist"
binding = "ASSETS"

[[routes]]
pattern = "hkaff2025.herballemon.dev/*"
zone_name = "herballemon.dev"

[vars]
ENVIRONMENT = "production"
